### ISSUE TITLE
Crash!

### ISSUE THREAD

**Issue by OstenTV** [Hialus/DeviceUtils#1]
[crash-2017-12-05_20.26.09-client.txt](https://github.com/Hialus/DeviceUtils/files/1532604/crash-2017-12-05_20.26.09-client.txt)

**Comment by Hialus** [comment]
Fixed it. I uploaded a not correctly compiled jar.

**Comment by OstenTV** [comment]
If you could compile it, I would be a happy man :)

2017-12-06 14:27 GMT+01:00 Hialus <notifications@github.com>:
